### PR TITLE
Fix the sample

### PR DESCRIPTION
**Pull request by agektmr**
The sample code is not workable.

***
<a href="https://pr-preview.s3.amazonaws.com/agektmr/FedCM/pull/144.html" title="Last updated on Nov 5, 2021, 8:13 AM UTC (c4b153f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/FedCM/144/af89185...agektmr:c4b153f.html" title="Last updated on Nov 5, 2021, 8:13 AM UTC (c4b153f)">Diff</a>

### CODE REVIEW

**Review by dj2 — APPROVED** [review]
LGTM

**Review by dj2 — COMMENTED** [review]
Actually, I'm wrong, the identityProvider is also used further down in another function, so this won't work as is either. Specifically, the revoke method.

**Comment by samuelgoto** [comment]
Should we drop this PR?

**Comment by agektmr** [comment]
I consider this obsoleted.

**Pull request closed without merging**
