### PR TITLE
Remove note on IdP to validate nonce (#582)

### PR DESCRIPTION
**Pull request by obfuscoder**
***
<a href="https://pr-preview.s3.amazonaws.com/obfuscoder/FedCM/pull/583.html" title="Last updated on May 15, 2024, 7:45 AM UTC (5ed1cf3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/583/82db3af...obfuscoder:5ed1cf3.html" title="Last updated on May 15, 2024, 7:45 AM UTC (5ed1cf3)">Diff</a>

### CODE REVIEW

**Comment by cbiesinger** [comment]
lgtm but could you resolve the IPR issue as described in https://labs.w3.org/repo-manager/pr/id/fedidcg/FedCM/583 ?

**Comment by samuelgoto** [comment]
LGTM++

**Comment by npm1** [comment]
Yea ideally you can fix the affiliation. But I'm also open to consider this a non-substantive change since it just removes a note

**Comment by obfuscoder** [comment]
As this PR is just about removing content, you could probably waive this requirement for this one. I'll try to get this IPR sorted out with my company, but it willl probably take a while.

**Comment by samuelgoto** [comment]
SGTM.

Waving as non-substantive.

**Pull request merged**
