### PR TITLE
Make providers required in IdentityCredentialRequestOptions

### PR DESCRIPTION
**Pull request by npm1**
@bvandersloot-mozilla WDYT

***
<a href="https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/pull/480.html" title="Last updated on Jun 21, 2023, 6:11 PM UTC (b42f622)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/480/fc286f7...b42f622.html" title="Last updated on Jun 21, 2023, 6:11 PM UTC (b42f622)">Diff</a>

### CODE REVIEW

**Comment by bvandersloot-mozilla** [comment]
This doesn't actually make much difference functionally- The list can still be empty. It does remove one of two empty list cases, so I don't mind the change.

**Comment by samuelgoto** [comment]
Why is this needed? 

I'm wondering how it relates to Adam's [PR5](https://github.com/agl/identity-credential) and if it makes it easier/harder.

**Comment by cbiesinger** [comment]
It is not strictly "needed" but it makes the IDL reflect the semantics better and could provide a slightly better error message (from bindings code) if JS code does not provide a providers property.

Adam's proposal is unaffected as written.

**Comment by npm1** [comment]
What Christian said :)

**Comment by npm1** [comment]
Ping

**Comment by bvandersloot-mozilla** [comment]
LGTM

**Pull request merged**
