### PR TITLE
Dont use well-known for the Manifest file

### PR DESCRIPTION
**Pull request by samuelgoto**

### CODE REVIEW

**Review by dj2 — APPROVED** [review]
LGTM. Has this change landed in Chrome already and rolled out? Or should we hold off landing this until it's in Chrome? (Or should we list both and point out what Chrome version it will hit stable?)

**Review by cbiesinger — APPROVED** [review]
lgtm but could you link to https://github.com/fedidcg/FedCM/issues/160 ?

**Comment by cbiesinger** [comment]
@dj2 not in chrome yet

**Comment by samuelgoto** [comment]
> LGTM. Has this change landed in Chrome already and rolled out? Or should we hold off landing this until it's in Chrome? (Or should we list both and point out what Chrome version it will hit stable?)

I'll kick off a crbug to track the implementation.

**Pull request merged**
