### PR TITLE
Make revoke() a non-static method

### PR DESCRIPTION
**Pull request by cbiesinger**
Fixes: #121

***
<a href="https://pr-preview.s3.amazonaws.com/cbiesinger/WebID/pull/139.html" title="Last updated on Nov 3, 2021, 10:08 PM UTC (b6204db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/FedCM/139/2ae2dc6...cbiesinger:b6204db.html" title="Last updated on Nov 3, 2021, 10:08 PM UTC (b6204db)">Diff</a>

### CODE REVIEW

**Comment by dj2** [comment]
This change LGTM. As pointed out in the issue, the examples aren't quite right because our `FederatedCredential` isn't quite right, but these examples match `Example 20` in the spec and so I think we could land this and then do a followup to update `FederatedCredential` to have a `FederatedIdentityProvider` and then use that to store the `provider` and `client_id`.

**Review by dj2 — APPROVED** [review]

**Comment by cbiesinger** [comment]
("the issue" Dan is referring to is #138 )

**Comment by samuelgoto** [comment]
Is this PR now outdated given @dj2 's recent changes to the v1.5 API? Can I close this?

**Comment by cbiesinger** [comment]
Yep

**Pull request closed without merging**
