### PR TITLE
Fix LogoutRPs

### PR DESCRIPTION
**Pull request by npm1**
Fixes https://github.com/fedidcg/FedCM/issues/373

***
<a href="https://pr-preview.s3.amazonaws.com/npm1/FedCM/pull/375.html" title="Last updated on Nov 17, 2022, 7:11 PM UTC (f9ff5a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/375/f782e3d...npm1:f9ff5a4.html" title="Last updated on Nov 17, 2022, 7:11 PM UTC (f9ff5a4)">Diff</a>

### CODE REVIEW

**Comment by npm1** [comment]
@bvandersloot-mozilla could you take a look?

**Comment by bvandersloot-mozilla** [comment]
LGTM, thanks for the quick response!

**Comment by npm1** [comment]
Thanks for the quick review!

**Comment by samuelgoto** [comment]
Isn't this backwards incompatible? That is, today, RPs take GET requests, NOT POST requests in their front channel logout endpoint, because that's implemented with iframes, right?

**Pull request merged**
